#!/usr/bin/env ruby
# encoding: utf-8

$:.push("./lib")
require "fifocache"

=begin
cache = Fifocache::new(100000)
100000.times do |i|
    cache[i] = i
end

exit
=end
cache = Fifocache::new(3, :puts => true)
cache[:alfa] = 'alfa'
cache[:beta] = 'beta'
cache[:gama] = 'gama'
cache[:delta] = 'delta'     # in this moment, :alfa is removed

puts cache.to_h.inspect

cache[:beta] = 'beta'      # :beta, :gama, :delta in cache
cache[:alfa] = 'alfa'      # :beta, :delta, :alfa in cache

puts cache.to_h.inspect

cache.hits = true           # you can do it in costructor too   
puts cache[:delta]          # cache hit
cache[:gama] = 'gama'       # :beta, :delta, :gama in cache

puts cache.to_h.inspect

cache.resize(0)

puts cache.to_h.inspect

